# Generated by Django 4.0.6 on 2022-08-09 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='profile_picture/avatar.svg', null=True, upload_to='profile_picture'),
        ),
    ]
